  express-mongo:
    build: .
    # image: shintech/express-mongo:latest
    container_name: express-mongo
    env_file:
      - ./express.env
    restart: always
    links:
      - mongo
    ports:
      - "8000:8000" 
      
  mongo:
    build: mongo
    # image: mongo:latest
    container_name: mongo
    env_file:
        - ./mongo.env
    volumes:
      - ./data/mongo:/data
    restart: always
