version: '3'

services: 
  express-mongo:
    build: .
    container_name: express-mongo
    env_file:
      - ./express.env
    restart: always
    links:
      - mongo
    ports:
      - "8000:8000" 
      
  mongo:
    container_name: mongo
    image: shintech/shintech-mongo:latest
    env_file:
        - ./mongo.env
    volumes:
      - ./data/mongo:/data/db
    restart: always
